In [ ]:
# prompt: please provide a small tutorial on NUMPY

import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

# Array with zeros
zeros = np.zeros((2,3))
print(zeros)

# Array with ones
ones = np.ones((3,2))
print(ones)

# Array with a range of elements
range_arr = np.arange(10,20,2)
print(range_arr)

# Array with random numbers
random_arr = np.random.rand(3,3)
print(random_arr)

# Array with evenly spaced numbers over a specified interval
linspace_arr = np.linspace(0, 1, 10)
print(linspace_arr)

# Reshape an array
reshaped_arr = arr.reshape(5,1)
print(reshaped_arr)

# Array indexing
print(arr[0])  # Access the first element
print(arr[1:4])  # Access elements from index 1 to 3
print(arr[-1])  # Access the last element

# Array operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)  # Element-wise addition
print(arr1 * arr2)  # Element-wise multiplication
print(np.dot(arr1, arr2))  # Dot product

# Array statistics
print(np.mean(arr))  # Mean
print(np.sum(arr))  # Sum
print(np.max(arr))  # Maximum value
print(np.min(arr))  # Minimum value


In [17]:
#import numpy library
import numpy as np

a=np.array([1,2,3,])
b=np.array([[1,2],[3,4]])
x=np.array(1)
print(x)
print (a)
print(b)

print(a.shape)
print(a.dtype)
print(a.ndim)

print(b.shape)

y=np.array([[1,2,3],[4,5,6],[3,2,1]])
print(y.shape)

z=np.array([[1,2,3],[1,2,3],[3,4,5],[2,3,4]])
print(z.shape)

print(z.reshape(3,4))





1
[1 2 3]
[[1 2]
 [3 4]]
(3,)
int64
1
(2, 2)
(3, 3)
(4, 3)
[[1 2 3 1]
 [2 3 3 4]
 [5 2 3 4]]


In [26]:
arr=np.array([[[1,2],[3,4]]])
arr
print(arr.shape)

(1, 2, 2)


In [33]:
arr=np.array([[[1,2]],[[3,4]],[[5,6]]])
print(arr)
print(arr.shape)

[[[1 2]]

 [[3 4]]

 [[5 6]]]
(3, 1, 2)
